version: "2"

volumes:
    mautic-db:
      driver: local
    redis-db:
      driver: local

services:

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis-db:/data

  mauticdb:
    image: mysql:5.6
    restart: always
    environment:
         MYSQL_ROOT_PASSWORD: mautic
         MYSQL_DATABASE: mautic
         MYSQL_USER: mautic
         MYSQL_PASSWORD: mautic
    volumes:
         - mautic-db:/var/lib/mysql

  mautic:
    image: trydirect/mautic:2.15.0
    container_name: mautic
    restart: always
    links:
      - mauticdb
    ports:
      - "8080"
    environment:
      MAUTIC_DB_HOST: mauticdb
      MYSQL_PORT_3306_TCP: 3306
      MAUTIC_DB_USER: mautic
      MAUTIC_DB_PASSWORD: mautic
      MAUTIC_DB_NAME: mautic

# entry point
  nginx:
    image: trydirect/nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - mautic
    ports:
      - "80:80"
      - "443:443"
    links:
      - mautic
    volumes:
      - ./certs/ssl:/etc/nginx/ssl
      - ./certs/letsencrypt:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./supervisord:/etc/supervisor/conf.d/
      - ./cron/nginx:/var/spool/cron/crontabs
    entrypoint: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n
